---
- name: Remove Nginx
  hosts: target_server
  become: yes
  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: Remove Nginx
      apt:
        name: nginx
        state: absent
