---
- name: Revert Nginx installation
  hosts: target_server
  become: yes
  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: Uninstall Nginx
      apt:
        name: nginx
        state: absent
