---
- name: Revert Sample Application Deployment
  hosts: target_server
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Stop the application service
      systemd:
        name: flask-app
        state: stopped

    - name: Remove application files
      file:
        path: /opt/sample-app
        state: absent

    - name: Remove systemd service file
      file:
        path: /etc/systemd/system/flask-app.service
        state: absent

    - name: Reload systemd to apply changes
      systemd:
        daemon_reload: yes

    - name: Remove MySQL user
      mysql_user:
        name: sample_user
        host: localhost
        state: absent

    - name: Drop database
      mysql_db:
        name: sample_db
        state: absent

    - name: Uninstall necessary packages
      apt:
        name:
          - python3-pip
          - default-libmysqlclient-dev
          - mysql-server
          - python3-mysql.connector
        state: absent
