---
- name: Deploy Sample Application
  hosts: target_server
  become: yes
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - python3-pip
          - python3-mysqldb
          - mysql-server
        state: present
        update_cache: yes

    - name: Install mysqlclient
      pip:
        name: mysqlclient
        executable: pip3

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database and user
      mysql_db:
        name: sample_db
        state: present

    - name: Create a MySQL user
      mysql_user:
        name: sample_user
        password: sample_pass
        priv: 'sample_db.*:ALL'
        state: present

    - name: Clone the application repository
      git:
        repo: 'https://github.com/Karlis-Zakis-KZ/m1p1'
        dest: /opt/sample-app
        version: main

    - name: Install application dependencies
      pip:
        requirements: /opt/sample-app/requirements.txt
        executable: pip3

    - name: Configure and start the application service
      systemd:
        name: flask-app
        enabled: yes
        state: started
        exec_start: /usr/bin/python3 /opt/sample-app/app.py
