---
- name: Deploy Sample Application
  hosts: target_server
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - python3-pip
          - default-libmysqlclient-dev
          - mysql-server
          - python3-mysql.connector
          - python3-mysqldb
        state: present
        update_cache: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database
      mysql_db:
        name: sample_db
        state: present

    - name: Create MySQL user
      mysql_user:
        name: sample_user
        password: sample_pass
        priv: 'sample_db.*:ALL'
        state: present

    - name: Clone the application repository
      git:
        repo: 'https://github.com/Karlis-Zakis-KZ/m1p1'
        dest: /opt/sample-app
        version: main

    - name: Install application dependencies
      pip:
        requirements: /opt/sample-app/requirements.txt
        executable: /usr/bin/pip3

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/flask-app.service
        content: |
          [Unit]
          Description=Flask Application

          [Service]
          ExecStart=/usr/bin/python3 /opt/sample-app/app.py
          Restart=always
          User=root
          Group=root
          Environment=PYTHONUNBUFFERED=1

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to register the flask-app service
      systemd:
        daemon_reload: yes

    - name: Start and enable flask-app service
      systemd:
        name: flask-app
        enabled: yes
        state: started
