---
- name: Deploy Sample Flask Application
  hosts: target_server
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - python3-pip
          - default-libmysqlclient-dev
          - mysql-server
          - python3-mysql.connector
          - python3-venv
        state: present
        update_cache: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database
      mysql_db:
        name: sample_db
        state: present

    - name: Create MySQL user
      mysql_user:
        name: sample_user
        password: sample_pass
        priv: 'sample_db.*:ALL'
        state: present

    - name: Clone the application repository
      git:
        repo: 'https://github.com/jainamoswal/Flask-Example'
        dest: /opt/sample-app
        version: main

    - name: Create a virtual environment
      command: python3 -m venv /opt/sample-app/venv

    - name: Install application dependencies in the virtual environment
      command: /opt/sample-app/venv/bin/pip install -r /opt/sample-app/requirements.txt

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/flask-app.service
        content: |
          [Unit]
          Description=Flask Application

          [Service]
          ExecStart=/opt/sample-app/venv/bin/python /opt/sample-app/run.py
          Restart=always
          User=root
          Group=root
          Environment=PYTHONUNBUFFERED=1

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to register the flask-app service
      systemd:
        daemon_reload: yes

    - name: Start and enable flask-app service
      systemd:
        name: flask-app
        enabled: yes
        state: started
