---
- name: Deploy Sample Application
  hosts: target_server
  become: yes
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - git
          - python3
          - python3-pip
          - mysql-server
        state: present
        update_cache: yes

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database and user
      mysql_db:
        name: sampledb
        state: present
        login_user: root
        login_password: your_root_password
    - mysql_user:
        name: sampleuser
        password: samplepassword
        priv: 'sampledb.*:ALL'
        state: present
        login_user: root
        login_password: your_root_password

    - name: Clone the application repository
      git:
        repo: 'https://github.com/sample/sample-app.git'
        dest: /opt/sample-app

    - name: Install application dependencies
      pip:
        requirements: /opt/sample-app/requirements.txt

    - name: Configure the application
      template:
        src: templates/config.j2
        dest: /opt/sample-app/config.ini

    - name: Ensure the application is running
      systemd:
        name: sample-app
        state: started
        enabled: yes
